# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import comunicacion_pb2 as comunicacion__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in comunicacion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegistroServiceStub(object):
    """El servicio que el Nodo D ofrece
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarNodo = channel.unary_unary(
                '/p2p.RegistroService/RegistrarNodo',
                request_serializer=comunicacion__pb2.SolicitudRegistro.SerializeToString,
                response_deserializer=comunicacion__pb2.ListaNodos.FromString,
                _registered_method=True)


class RegistroServiceServicer(object):
    """El servicio que el Nodo D ofrece
    """

    def RegistrarNodo(self, request, context):
        """Un nodo C se registra y obtiene la lista de nodos activos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarNodo': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarNodo,
                    request_deserializer=comunicacion__pb2.SolicitudRegistro.FromString,
                    response_serializer=comunicacion__pb2.ListaNodos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'p2p.RegistroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('p2p.RegistroService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegistroService(object):
    """El servicio que el Nodo D ofrece
    """

    @staticmethod
    def RegistrarNodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.RegistroService/RegistrarNodo',
            comunicacion__pb2.SolicitudRegistro.SerializeToString,
            comunicacion__pb2.ListaNodos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SaludoServiceStub(object):
    """Servicio para saludos entre Nodos C (Opcional, para simetría)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarSaludo = channel.unary_unary(
                '/p2p.SaludoService/EnviarSaludo',
                request_serializer=comunicacion__pb2.MensajeSaludo.SerializeToString,
                response_deserializer=comunicacion__pb2.Confirmacion.FromString,
                _registered_method=True)


class SaludoServiceServicer(object):
    """Servicio para saludos entre Nodos C (Opcional, para simetría)
    """

    def EnviarSaludo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SaludoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarSaludo': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarSaludo,
                    request_deserializer=comunicacion__pb2.MensajeSaludo.FromString,
                    response_serializer=comunicacion__pb2.Confirmacion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'p2p.SaludoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('p2p.SaludoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SaludoService(object):
    """Servicio para saludos entre Nodos C (Opcional, para simetría)
    """

    @staticmethod
    def EnviarSaludo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.SaludoService/EnviarSaludo',
            comunicacion__pb2.MensajeSaludo.SerializeToString,
            comunicacion__pb2.Confirmacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
