# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comunicacion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'comunicacion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63omunicacion.proto\x12\x03p2p\"/\n\x11SolicitudRegistro\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0e\n\x06puerto\x18\x02 \x01(\x05\"&\n\x08NodoInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0e\n\x06puerto\x18\x02 \x01(\x05\"*\n\nListaNodos\x12\x1c\n\x05nodos\x18\x01 \x03(\x0b\x32\r.p2p.NodoInfo\"2\n\rMensajeSaludo\x12\x0e\n\x06\x65misor\x18\x01 \x01(\t\x12\x11\n\tcontenido\x18\x02 \x01(\t\"\x1e\n\x0c\x43onfirmacion\x12\x0e\n\x06status\x18\x01 \x01(\t2M\n\x0fRegistroService\x12:\n\rRegistrarNodo\x12\x16.p2p.SolicitudRegistro\x1a\x0f.p2p.ListaNodos\"\x00\x32H\n\rSaludoService\x12\x37\n\x0c\x45nviarSaludo\x12\x12.p2p.MensajeSaludo\x1a\x11.p2p.Confirmacion\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comunicacion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOLICITUDREGISTRO']._serialized_start=27
  _globals['_SOLICITUDREGISTRO']._serialized_end=74
  _globals['_NODOINFO']._serialized_start=76
  _globals['_NODOINFO']._serialized_end=114
  _globals['_LISTANODOS']._serialized_start=116
  _globals['_LISTANODOS']._serialized_end=158
  _globals['_MENSAJESALUDO']._serialized_start=160
  _globals['_MENSAJESALUDO']._serialized_end=210
  _globals['_CONFIRMACION']._serialized_start=212
  _globals['_CONFIRMACION']._serialized_end=242
  _globals['_REGISTROSERVICE']._serialized_start=244
  _globals['_REGISTROSERVICE']._serialized_end=321
  _globals['_SALUDOSERVICE']._serialized_start=323
  _globals['_SALUDOSERVICE']._serialized_end=395
# @@protoc_insertion_point(module_scope)
